### ISSUE TITLE
windbg6.3不起作用

### ISSUE THREAD

**Issue by DragonQuestHero** [lynnux/windbg_hilight#3]
看了一下最后一次提交是3年前
不知道有兴趣更新下么...

**Comment by lynnux** [comment]
抱歉现在才有时间回复，我从这里下载http://codemachine.com/downloads.html的安装包，经测试，Windows 10 Version 1607的x86可用（X64好像没安装成功，没找到exe，win7 64机子），然后本身装了个WDK8.1自带的windbg版本就是6.3，经测试x86/x64都可以使用。
还有个windbg preview估计win7装不上也就没有测试了。

**Comment by DragonQuestHero** [comment]
没事 我以为你都不更新了
我刚刚又试了一次 还是不行
我是WDK8.1自带的windbg
DLL放到C:\Program Files (x86)\Windows Kits\8.1\Debuggers\x64下
.load hs64 然后删除DLL 提示已windbg已占用
也没有看到哪里生成了windbg_hilight.ini
在家和在公司都试了 一样的效果
win10 x64 1607

**Comment by lynnux** [comment]
windbg_hilight.ini没有正常，以管理员运行才有，没有的话就是默认配色。
hs64被占用那应该是加载 了，注意在命令窗口，u显示汇编是没效果的，只有alt+7汇编窗口有效果。
刚测试win10 32位也是可以的

**Comment by DragonQuestHero** [comment]
管理员权限下也没有
汇编窗口也没有效果...

**Comment by lynnux** [comment]
神奇了，刚在家里win8.1上试了windbg v10也是可以的。这个可能需要你自己编译/调试下看了，原理很简单就是hook ExtTextOutW，要么是hook没成功，要么就是hook里的处理有问题。

**Comment by DragonQuestHero** [comment]
这就尴尬了233 我一直都是直接去百度云地址下的...
我弄下来编译调下看看 多谢了
